language: go
go:
  - 1.10.x
  - tip
addons:
  apt:
    chrome: stable
before_install:
  - go get github.com/mattn/goveralls golang.org/x/vgo
script:
  - vgo build && ./cdproto-gen
  - cd $GOPATH/src/github.com/chromedp/cdproto
  - go install ./...
