language: go
go:
  - 1.11.x
  - 1.12.x
addons:
  apt:
    chrome: stable
before_install:
  - go get -u github.com/chromedp/cdproto
script:
  - export GO111MODULE=on
  - go build && ./cdproto-gen
  - cd $GOPATH/src/github.com/chromedp/cdproto
  - go install ./...
